name: GetPerms
author: Smiley43210
description: Plugin to automatically generate files containing permission nodes for plugins installed on the server.
main: com.github.GetPerms.GetPerms.Main
version: 1.1.14
commands:
  getperms:
    description: Main plugin command.
    usage: /<command> <reload|regen|update>
  gp:
    description: Main plugin command.
    usage: /<command> <reload|regen|update>
permissions:
  getperms.*:
    description: Allows player access to all GetPerms commands.
    children:
      getperms.reload: true
      getperms.regen: true
      getperms.update: true
  getperms.reload:
    description: Allows player to reload the GetPerms config file.
    default: op
  getperms.regen:
    description: Allows player to regenerate permission list files.
    default: op
  getperms.update:
    description: Allows player to run the update task.
    default: op