#GetPerms config

#Is it the first run?
firstRun: true

#Weather or not to automatically generate the permissions files on startup
autoGen: true

#Weather or not to check for updates
autoUpdate: true

#Should it automatically download the newest GetPerms.jar?
autoDownload: false

#Debug if needed
debugMode: false
